dashboard/urls.py
from django.urls import path
from dashboard import views
app_name = 'dashboard'
urlpatterns = [ 
    path('create', views.dashboard_index ,name="index"),
    path('libraries', views.dashboard_libraries ,name="libraries"),
    path('delete_claim/<int:librabry_id>', views.delete_claim , name="delete_claim"),
    path('upload_data', views.upload_data , name="upload_data"),
   
    

    
    


    
 
]

home/urls.py
from django.urls import path
from home import views
app_name = 'home'
urlpatterns = [ 
    
    path('', views.home_login , name="login"),
    path('logout', views.home_logout ,name="logout"),
    path('profile', views.home_profile ,name="profile"),


]

medclaim/urls.py
from django.contrib import admin
from django.urls import path
from home import urls as home_urls
from mainmenu import urls as mainmenu_urls
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from dashboard import urls as dashboard_urls

urlpatterns = [
    path('', include(home_urls, namespace="home")),
    path('mainmenu/', include(mainmenu_urls, namespace="mainmenu")),
    path('dashboard/', include(dashboard_urls, namespace="dashboard")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = 'Medclaim'
admin.site.site_title = 'Medclaim'

dashboard/models.py
from django.db import models
from medclaim.settings import MEDIA_ROOT
class Provider(models.Model):

    provider_id  = models.CharField(default=None ,max_length=100)
    potential_fraud = models.CharField(default=None ,max_length=100)

    def __str__(self):
        return '%s' % self.provider_id+" potential fraud :"+self.potential_fraud

class Beneficiary(models.Model):

    beneficiary_id  = models.CharField(default=None ,max_length=100)
  

    def __str__(self):
        return '%s' % self.beneficiary_id+" Hidden Name & Surname"

class Physician(models.Model):

    physician_id  = models.CharField(default=None ,max_length=100)
  

    def __str__(self):
        return '%s' % self.physician_id

class Library(models.Model):
    
    GENDER = (('', '------'), ('0', 'Male'),('1', 'Female'),)
    # provider details
    provider_id = models.ForeignKey(Provider,on_delete=models.CASCADE , default=None)
   
    # physician details
    physician_id = models.ForeignKey(Physician,on_delete=models.CASCADE , default=None)
    operating_physician = models.ForeignKey(Physician,related_name='operating_physician' , on_delete=models.CASCADE , default=None)
    
    other_physician = models.ForeignKey(Physician,related_name='other_physician' , on_delete=models.CASCADE , default=None)
    # patient details
    patient_id = models.ForeignKey(Beneficiary,on_delete=models.CASCADE , default=None)
    gender = models.CharField(blank=True ,null=True, default='no' ,max_length=100 , choices = GENDER)
    race = models.CharField(default=None ,max_length=100)
    state = models.CharField(default=None ,max_length=100)
    country = models.CharField(default=None ,max_length=100)
    RenalDiseaseIndicator = models.CharField(default=None,max_length=100 , choices = (('', '------'), ('1', 'Yes'),('0', 'No'),))
    Alzheimer  = models.CharField(default=None,max_length=100 , choices = (('', '------'), ('1', 'Yes'),('0', 'No'),))
    Heartfailure  = models.CharField(default=None,max_length=100 , choices = (('', '------'), ('1', 'Yes'),('0', 'No'),))
    KidneyDisease  = models.CharField(default=None,max_length=100 , choices = (('', '------'), ('1', 'Yes'),('0', 'No'),))
    Cancer = models.CharField(default=None,max_length=100 , choices = (('', '------'), ('1', 'Yes'),('0', 'No'),))
    ObstrPulmonary = models.CharField(default=None,max_length=100 , choices = (('', '------'), ('1', 'Yes'),('0', 'No'),))
    Depression  = models.CharField(default=None,max_length=100 , choices = (('', '------'), ('1', 'Yes'),('0', 'No'),))
    Diabetes  = models.CharField(default=None,max_length=100 , choices = (('', '------'), ('1', 'Yes'),('0', 'No'),))
    IschemicHeart  = models.CharField(default=None,max_length=100 , choices = (('', '------'), ('1', 'Yes'),('0', 'No'),))
    Osteoporasis  = models.CharField(default=None,max_length=100 , choices = (('', '------'), ('1', 'Yes'),('0', 'No'),))
    Arthritis  = models.CharField(default=None,max_length=100 , choices = (('', '------'), ('1', 'Yes'),('0', 'No'),))
    Stroke  = models.CharField(default=None,max_length=100 , choices = (('', '------'), ('1', 'Yes'),('0', 'No'),))
    # Treatment details
    diagnosis_1 = models.CharField(default=0 ,max_length=100)
    diagnosis_2 = models.CharField(default=0 ,max_length=100)
    diagnosis_3 = models.CharField(default=0 ,max_length=100)
    diagnosis_4 = models.CharField(default=0 ,max_length=100)
    diagnosis_5 = models.CharField(default=0 ,max_length=100)
    diagnosis_6 = models.CharField(default=0 ,max_length=100)
    diagnosis_7 = models.CharField(default=0 ,max_length=100)
    diagnosis_8 = models.CharField(default=0 ,max_length=100)
    diagnosis_9 = models.CharField(default=0 ,max_length=100)
    diagnosis_10 = models.CharField(default=0 ,max_length=100)

    # procedure details
    procedure_1 = models.CharField(default=0 ,max_length=100)
    procedure_2 = models.CharField(default=0 ,max_length=100)
    procedure_3 = models.CharField(default=0 ,max_length=100)
    procedure_4 = models.CharField(default=0 ,max_length=100)
    procedure_5 = models.CharField(default=0 ,max_length=100)
    procedure_6 = models.CharField(default=0 ,max_length=100)

    # other group codes details
    DiagnosisGroupCode  = models.CharField(default=0 ,max_length=100)
    ClmAdmitDiagnosisCode   = models.CharField(default=0 ,max_length=100)

    no_of_days_admitted = models.IntegerField(default=None)
    no_of_days_for_claim = models.IntegerField(default=None)

    # insurance amounts reimbursed by patient
    total_insurance_reimbursed = models.IntegerField(default=None)
    total_deductable_paid = models.IntegerField(default=None)
    amount_reimbursed_as_inpatient = models.IntegerField(default=None)
    amount_reimbursed_as_outpatient = models.IntegerField(default=None)
    total_deductable_paid_as_outpatient = models.IntegerField(default=None)
    is_fraudulent = models.BooleanField(default=False)
    updated_at = models.DateField(default=None)
    created_by = models.IntegerField(default=None)

    

    def __str__(self):
        return '%s' % self.application_name

dashboard/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator
from dashboard.models import Library 

# model form 
from django.db import models
# from django.forms import ModelForm , Textarea , ModelChoiceField , Select  
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class Library_Form(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'id-exampleForm'
        self.helper.form_class = 'form-horizontal mr-auto ml-auto'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-6'
        self.helper.form_method = 'post'
        self.helper.form_action = 'submit_survey'

        self.helper.add_input(Submit('submit', 'Submit Claim for Processing'))
        
    class Meta:
        model = Library
        
        
        fields = ['provider_id','physician_id','operating_physician','other_physician','patient_id','gender' ,'race','state',
                    'country','RenalDiseaseIndicator','Alzheimer','Heartfailure','KidneyDisease','Cancer','ObstrPulmonary','Depression',
                    'Diabetes','IschemicHeart','Osteoporasis','Arthritis','Stroke','diagnosis_1','diagnosis_2','diagnosis_3','diagnosis_4',
                    'diagnosis_5','diagnosis_6','diagnosis_7','diagnosis_8','diagnosis_9','diagnosis_10','procedure_1','procedure_2','procedure_3',
                    'procedure_4','procedure_5','procedure_6','DiagnosisGroupCode','ClmAdmitDiagnosisCode','no_of_days_admitted','no_of_days_for_claim',
                    'total_insurance_reimbursed','total_deductable_paid','amount_reimbursed_as_inpatient','amount_reimbursed_as_outpatient',
                    'total_deductable_paid_as_outpatient' 
                ]

             
   

dashboard/views.py
from django.shortcuts import render
import calendar
from datetime import datetime
from django.contrib.auth.decorators import login_required , permission_required
from django.urls.base import translate_url
from requests.api import head
from pypi_simple import PyPISimple 
from dashboard.forms import Library_Form 
from dashboard.models import  Library, Physician, Provider , Beneficiary
from django.contrib import messages
from django.utils import timezone
from django.urls import reverse
from django.http import HttpResponseRedirect
import vulners  
from django.core.mail import send_mail
import random
import pandas as pd
import requests
import json
from io import StringIO
import base64

from sklearn.cluster import KMeans
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from matplotlib import pyplot as plt
from time import sleep
from medclaim.settings import MEDIA_ROOT



@login_required
def dashboard_index(request):
    form = None
    url = "dashboard/index.html" 
    if request.method == 'POST':
        form = Library_Form(request.POST, request.FILES)
        if(form.is_valid()):
            data = form.save(commit=False)
        
            
            data.created_at = timezone.now()
            data.updated_at = timezone.now()
            data.created_by = request.user.id   
            data.save()
            messages.add_message(request, messages.INFO, 'File saved')
            return HttpResponseRedirect(reverse('dashboard:libraries'))
     
    else:
        form = Library_Form()
    
    context = {
         
        'title': "Claim submission portal",
        'form':form
        
    } 
     
    return render(request , url , context)






def dashboard_libraries(request):
    libraries = Library.objects.all().order_by('-id')
    url = "dashboard/list_librabries.html" 
 
    context = {
        
        'title': "Listing claims",
        'libraries':libraries
        
    } 


    return render(request , url , context)


@login_required
def delete_claim(request ,librabry_id=None):
    library = Library.objects.get(pk=librabry_id)
    library.delete()
    messages.add_message(request, messages.INFO, 'Library deleted')
    return HttpResponseRedirect('/dashboard/libraries')


def upload_data(request):

    if request.method == 'POST':
        pass
    elif request.method == 'GET':
        import pandas as pd

        df = pd.read_csv(MEDIA_ROOT+"/uploads/Train_Inpatientdata-1542865627584.csv")


        for index, row in df.iterrows():

           
            data = {}
            data['physician_id'] = row['OperatingPhysician']
            # data['potential_fraud'] = row['PotentialFraud']

            # data['nationality'] = row['replace']
            # data['allergies'] = row['replace']
            # data['medical_aid_scheme'] = row['replace']
            # data['medical_aid_number'] = row['replace']
            # data['next_of_kin_name'] = row['replace']
            # data['next_of_kin_phone_number'] = row['replace']
           

            provider = Physician.objects.create(**data)
            provider.save()
            print(data)
            print("_______________________________________________")
    context = {
        
        'title': "Data upload" ,
    }

    return render(request, 'dashboard/list_librabries.html', context)

dashboard/templates/dashboard/index.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% crispy library_form library_form.helper %}

{% load static %}
{% block header %}
    <link href="{% static "admin/assets/libs/bootstrap-datepicker/css/bootstrap-datepicker.min.css" %}" rel="stylesheet">
{% endblock %}
{% block content %}

<form action="" method="post" autocomplete="off" enctype="multipart/form-data">{% csrf_token %}
<div class="row">
    <div class="col-lg-12">
        <div class="card">  
            <div class="card-body">
        
                <table>{% crispy form %}</table>

                
            </div>
        </div>
    </div>
   
</div>

</form>
{% endblock %}


{% block footer %}

    <script>
        $('#id_data_mode').on('change', function() {
            if(this.value == "csv" | this.value == "text"){
                $('.data-file').css("display", 'block');
             
            }else{
                $('.data-file').css("display", 'none');
             
            }
        });
    </script>
    <script src="{% static "admin/assets/libs/bootstrap-datepicker/js/bootstrap-datepicker.min.js" %}"></script>
    <script src="{% static "admin/assets/js/pages/form-advanced.init.js" %}"></script>
    <script src="{% static "admin/assets/libs/bootstrap-maxlength/bootstrap-maxlength.min.js" %}"></script>
{% endblock %}

dashboard/templates/dashboard/list_librabries.html
{% extends "base.html" %}

{% load static %}
{% block header %}
    <link href="{% static "admin/assets/libs/bootstrap-datepicker/css/bootstrap-datepicker.min.css" %}" rel="stylesheet">
    <style>
        input[type="text"]:disabled {
        background: #dddddd;
}
    </style>
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-12">
        
        <a href="{% url 'dashboard:index' %}" class="btn btn-lg btn-success float-right">Capture Claim</a>
     
    </div>
    <br>
</div>



<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">


             
                <table class="table table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                    <thead>
                    <tr>
                        
                        <th>Provider ID </th>
                        <th>Physician ID</th>
                        <th>Operating Physician</th>
                        <th>Patient</th>
                        <th>Is Fraudulent  </th>
                        <th>Action  </th>
                        

                        
                    
                    </tr>
                    </thead>


                    <tbody>
                 
                    {% for item in libraries %}
                        <tr>
                            <td>{{item.provider_id}}</td>
                            <td>{{item.physician_id}}</td>
                            <td>{{item.operating_physician}}</td>
                            <td>{{item.patient_id}}</td>
                            <td>{{item.is_fraudulent}}</td>
                            

                        
                            <td>
   
                                
                               
                                <a href="#" class="btn btn-outline-success waves-effect waves-light" >View</a>
                                <a href="{% url  'dashboard:delete_claim' item.id %}" class="btn btn-outline-danger waves-effect waves-light" onclick="alert('Are you sure you want to delete')" >Delete</a>
                               
                            </td>
                 {% endfor %}        
                        </tr>
                   
               
              
                    </tbody>
                </table>

            </div>
        </div>
    </div> <!-- end col -->

</div> <!-- end row -->

{% endblock %}
    
{% block footer %}


  
<!-- datetime -->
<script src="{% static "admin/assets/libs/bootstrap-datepicker/js/bootstrap-datepicker.min.js" %}"></script>
<script src="{% static "admin/assets/js/pages/form-advanced.init.js" %}"></script>
<script src="{% static "admin/assets/libs/bootstrap-maxlength/bootstrap-maxlength.min.js" %}"></script>
     <!-- Required datatable js -->
     <script src="{% static "admin/assets/libs/datatables.net/js/jquery.dataTables.min.js" %}"></script>
     <script src="{% static "admin/assets/libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js" %}"></script>

     <!-- Datatable init js -->
     <script src="{% static "admin/assets/js/pages/datatables.init.js" %}"></script>
{% endblock %}